
version: '3.3'
services:
    api:
        build: .
        command: python -u app.py
        ports:
        - "80:5000"
        - "443:5000"
        volumes:
        - .:/app
        links:
        - db
    db:
        image: mongo